"""
Impact Domain Models — Exploitability analysis and business impact assessment.

ImpactReport is generated by the Impact Assessor Agent for each Finding.
It enriches raw CVE matches with LLM-reasoned exploitability analysis and
prioritisation, giving the Remediation Planner the context needed to triage
and schedule fixes.

Architectural note:
    Finding answers "Is this package vulnerable?"
    ImpactReport answers "Does it matter here, and how urgently?"

    The two are kept separate so ImpactReports can be regenerated
    (e.g. after new exploit info surfaces) without re-running the full scan.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from vulnremedy.models.finding import Finding


class Priority(str, Enum):
    """
    Business-level remediation priority.

    Differs from Severity in that it incorporates exploitability context,
    dependency path, and service exposure — not just the raw CVE score.

    CRITICAL — Exploitable now, production-facing, high business impact.
               Requires immediate action (same-day PR creation).
    HIGH     — Likely exploitable, or CRITICAL severity with uncertain path.
               Requires action within 24–48 hours.
    MEDIUM   — Potentially exploitable but mitigating factors exist.
               Requires action within the next sprint.
    LOW      — Not exploitable in context, or test/internal dependency only.
               Track but do not block deployments.
    """
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ImpactReport(BaseModel):
    """
    Impact assessment for a single Finding.

    Produced by the Impact Assessor Agent after LLM-assisted exploitability
    reasoning and RAG-augmented context retrieval.
    """
    id: UUID = Field(default_factory=uuid4)

    finding: Finding = Field(
        description="The original Finding this report is based on"
    )

    # Blast radius
    affected_services: list[str] = Field(
        default_factory=list,
        description=(
            "Services or repositories impacted by this vulnerability. "
            "Derived from the repository field and any cross-service dependency data."
        ),
    )
    dependency_path: list[str] = Field(
        default_factory=list,
        description=(
            "Chain from the top-level project to the vulnerable package. "
            "e.g. ['payment-service', 'pom.xml', 'org.apache.logging.log4j:log4j-core@2.14.1']. "
            "Shallow for direct deps, longer for transitive deps."
        ),
    )

    # LLM-generated exploitability analysis
    is_exploitable: bool = Field(
        description=(
            "Whether the vulnerability is actually reachable and exploitable "
            "in this specific deployment context, as assessed by the LLM."
        )
    )
    exploitability_reasoning: str = Field(
        description=(
            "LLM-generated explanation of why the CVE is or is not exploitable "
            "in this context. Includes code path analysis, exposure assessment, "
            "and mitigating factors."
        )
    )
    business_impact: str = Field(
        description=(
            "LLM-generated description of potential business consequences "
            "if this vulnerability is exploited — data exposure, downtime, "
            "compliance implications, etc."
        )
    )

    # Final priority (may differ from raw CVE severity after context analysis)
    priority: Priority = Field(
        description=(
            "Business-level remediation priority determined by the Impact Assessor. "
            "Incorporates severity, exploitability, service exposure, and fix availability."
        )
    )

    # Traceability
    llm_model_used: Optional[str] = Field(
        default=None,
        description="Which LLM model generated the analysis (for audit trail)"
    )
    used_fallback: bool = Field(
        default=False,
        description=(
            "True if the LLM call failed and a deterministic fallback was used. "
            "Downstream agents should treat fallback reports with lower confidence."
        )
    )
