"""
Remediation Domain Models — Fix plans and code changes.

A RemediationPlan is generated by the Remediation Planner agent
after analyzing a Finding. It contains the step-by-step fix strategy,
code changes needed, and approval workflow state.

Architectural note:
    RemediationPlan is separate from Finding because:
    - One Finding can have multiple remediation attempts (first plan fails, try different approach)
    - Remediation logic is complex enough to deserve its own model boundary
    - The PR Creator agent only cares about RemediationPlan, not the original Finding
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from vulnremedy.models.finding import Finding


class RemediationStrategy(str, Enum):
    """
    High-level remediation approach.
    
    Chosen by the Remediation Planner agent based on dependency type,
    ecosystem, and risk tolerance.
    """
    VERSION_UPGRADE = "version_upgrade"             # Direct dependency — bump version in manifest
    TRANSITIVE_OVERRIDE = "transitive_override"     # Transitive dep — add explicit override
    DEPENDENCY_EXCLUSION = "dependency_exclusion"   # Exclude vulnerable transitive dep
    BOM_OVERRIDE = "bom_override"                   # Maven BOM version management
    CODE_REFACTOR = "code_refactor"                 # Breaking change — code must be updated
    MANUAL_REVIEW = "manual_review"                 # Too complex — human must decide


class RemediationStatus(str, Enum):
    """
    Lifecycle state of a remediation plan.
    
    Tracks from generation through to deployment.
    """
    DRAFT = "draft"                     # Plan generated, not yet reviewed
    PENDING_APPROVAL = "pending_approval"  # Waiting for human approval
    APPROVED = "approved"               # Human approved, ready for PR creation
    PR_CREATED = "pr_created"           # PR created, waiting for merge
    DEPLOYED = "deployed"               # PR merged and deployed
    REJECTED = "rejected"               # Human rejected the plan
    FAILED = "failed"                   # PR creation or deployment failed


class CodeChange(BaseModel):
    """
    A single code change required for remediation.
    
    Represents one file modification — could be a manifest update,
    a config change, or actual source code refactoring.
    """
    file_path: str = Field(
        description="Path to file relative to repo root e.g. 'pom.xml', 'src/main/java/Config.java'"
    )
    change_type: str = Field(
        description="Type of change: 'version_bump', 'import_change', 'api_migration', 'config_update'"
    )
    original_content: Optional[str] = Field(
        default=None,
        description="Original file content or relevant section"
    )
    new_content: str = Field(
        description="New file content or diff to apply"
    )
    line_number: Optional[int] = Field(
        default=None,
        description="Starting line number for the change"
    )
    rationale: str = Field(
        description="Why this change is needed — helps humans review"
    )


class RemediationPlan(BaseModel):
    """
    Complete remediation plan for a Finding.
    
    Generated by the Remediation Planner agent.
    Consumed by the PR Creator agent.
    
    Architectural note:
        Contains everything needed to automatically create a PR:
        - Which files to change
        - What changes to make
        - Why each change is needed
        - Testing recommendations
"""
    id: UUID = Field(default_factory=uuid4)
    finding_id: UUID = Field(
        description="The Finding this plan remediates"
    )
    finding: Finding = Field(
        description="Embedded Finding for context — agents don't need to fetch it separately"
    )
    strategy: RemediationStrategy
    status: RemediationStatus = RemediationStatus.DRAFT
    
    code_changes: list[CodeChange] = Field(
        default_factory=list,
        description="All file changes needed to apply this fix"
    )
    
    # Human-readable plan
    summary: str = Field(
        description="One-sentence summary e.g. 'Upgrade log4j-core from 2.14.1 to 2.17.1'"
    )
    detailed_steps: list[str] = Field(
        default_factory=list,
        description="Step-by-step instructions for manual execution if needed"
    )
    breaking_changes: list[str] = Field(
        default_factory=list,
        description="API changes or incompatibilities introduced by this fix"
    )
    testing_recommendations: list[str] = Field(
        default_factory=list,
        description="What to test after applying this fix"
    )
    
    # Approval workflow
    requires_human_approval: bool = Field(
        default=True,
        description="If true, plan must be approved before PR creation"
    )
    approved_by: Optional[str] = Field(
        default=None,
        description="User who approved this plan"
    )
    approved_at: Optional[datetime] = Field(
        default=None,
        description="When approval was granted"
    )
    rejection_reason: Optional[str] = Field(
        default=None,
        description="Why this plan was rejected"
    )
    
    # Execution tracking
    pr_url: Optional[str] = Field(
        default=None,
        description="GitHub PR URL if PR was created"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow
    )

    @property
    def is_low_risk(self) -> bool:
        """
        Determine if this remediation is low-risk.
        
        Low-risk plans can potentially skip human approval.
        Criteria: direct version upgrade, no breaking changes, no code refactoring.
        """
        return (
            self.strategy == RemediationStrategy.VERSION_UPGRADE
            and len(self.breaking_changes) == 0
            and all(c.change_type == "version_bump" for c in self.code_changes)
        )

    def approve(self, approver: str) -> None:
        """
        Approve this remediation plan.
        
        Transitions status to APPROVED, records who approved and when.
        Called by API layer after human reviews the plan.
        """
        self.status = RemediationStatus.APPROVED
        self.approved_by = approver
        self.approved_at = datetime.utcnow()
        self.updated_at = datetime.utcnow()

    def reject(self, reason: str) -> None:
        """
        Reject this remediation plan.
        
        Transitions status to REJECTED, records why.
        Finding remains open — Remediation Planner can generate alternative plan.
        """
        self.status = RemediationStatus.REJECTED
        self.rejection_reason = reason
        self.updated_at = datetime.utcnow()

    def mark_pr_created(self, pr_url: str) -> None:
        """
        Mark that PR was successfully created.
        
        Called by PR Creator agent after GitHub API succeeds.
        """
        self.status = RemediationStatus.PR_CREATED
        self.pr_url = pr_url
        self.updated_at = datetime.utcnow()

    def mark_deployed(self) -> None:
        """
        Mark that fix was deployed.
        
        Called when PR is merged and deployed to production.
        At this point the Finding is also marked as REMEDIATED.
        """
        self.status = RemediationStatus.DEPLOYED
        self.updated_at = datetime.utcnow()